#!/bin/bash
# Script for change faust diagrams

sudo -v
echo insert the faust code name without dsp extension:
read faustcode
faust2firefox $faustcode.dsp
cd $faustcode-svg
echo the folder is:
pwd
mkdir converted
# converting to pdf
for i in *.svg; do rsvg-convert -f pdf -o converted/$i-converted.pdf $i; done
cd converted
# black and white pdf
for i in *.pdf; do gs \
 -sOutputFile=$i-BW.pdf \
 -sDEVICE=pdfwrite \
 -sColorConversionStrategy=Gray \
 -dProcessColorModel=/DeviceGray \
 -dCompatibilityLevel=1.4 \
 -dBlackText \
 -dNOPAUSE \
 -dBATCH \
 $i; done
# crop margins
for i in *.pdf; do pdf-crop-margins -v -p 0 -a -6 $i.pdf; done
echo all done!
